# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\darke\Documents\GitHub\Downoald_Manga_Novel\App\Gui\PreciseMangaView.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        self.PreciseMangaWidget = QtWidgets.QFrame(self.centralwidget)
        self.PreciseMangaWidget.setMinimumSize(QtCore.QSize(875, 550))
        self.PreciseMangaWidget.setObjectName("PreciseMangaWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.PreciseMangaWidget)
        self.verticalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.InfoManga = QtWidgets.QVBoxLayout()
        self.InfoManga.setContentsMargins(5, -1, 5, -1)
        self.InfoManga.setObjectName("InfoManga")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MangaImage = QtWidgets.QLabel(self.PreciseMangaWidget)
        self.MangaImage.setMinimumSize(QtCore.QSize(131, 181))
        self.MangaImage.setMaximumSize(QtCore.QSize(151, 180))
        self.MangaImage.setBaseSize(QtCore.QSize(151, 150))
        self.MangaImage.setText("")
        self.MangaImage.setPixmap(QtGui.QPixmap("c:\\Users\\darke\\Documents\\GitHub\\Downoald_Manga_Novel\\App\\Gui\\../../manga/The Villainess Want to Marry a Commoner/.3-yk918594-193x278.jpg"))
        self.MangaImage.setScaledContents(True)
        self.MangaImage.setObjectName("MangaImage")
        self.horizontalLayout_3.addWidget(self.MangaImage)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.MangaName = QtWidgets.QLabel(self.PreciseMangaWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.MangaName.setFont(font)
        self.MangaName.setWordWrap(True)
        self.MangaName.setObjectName("MangaName")
        self.verticalLayout.addWidget(self.MangaName)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MangaChapter = QtWidgets.QLabel(self.PreciseMangaWidget)
        self.MangaChapter.setObjectName("MangaChapter")
        self.verticalLayout_4.addWidget(self.MangaChapter)
        self.NovelChapter = QtWidgets.QLabel(self.PreciseMangaWidget)
        self.NovelChapter.setObjectName("NovelChapter")
        self.verticalLayout_4.addWidget(self.NovelChapter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.pushButton_4 = QtWidgets.QPushButton(self.PreciseMangaWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.Update = QtWidgets.QPushButton(self.PreciseMangaWidget)
        self.Update.setMinimumSize(QtCore.QSize(131, 41))
        self.Update.setBaseSize(QtCore.QSize(131, 41))
        self.Update.setObjectName("Update")
        self.horizontalLayout_2.addWidget(self.Update)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.InfoManga.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.InfoManga)
        self.AllListManga = QtWidgets.QGridLayout()
        self.AllListManga.setObjectName("AllListManga")
        self.NovelListLabel = QtWidgets.QLabel(self.PreciseMangaWidget)
        self.NovelListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NovelListLabel.setObjectName("NovelListLabel")
        self.AllListManga.addWidget(self.NovelListLabel, 0, 1, 1, 1)
        self.MangaListLabel = QtWidgets.QLabel(self.PreciseMangaWidget)
        self.MangaListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MangaListLabel.setObjectName("MangaListLabel")
        self.AllListManga.addWidget(self.MangaListLabel, 0, 0, 1, 1)
        self.NovelView = QtWidgets.QListWidget(self.PreciseMangaWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NovelView.setFont(font)
        self.NovelView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.NovelView.setModelColumn(0)
        self.NovelView.setWordWrap(True)
        self.NovelView.setObjectName("NovelView")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.NovelView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.NovelView.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.NovelView.addItem(item)
        self.AllListManga.addWidget(self.NovelView, 1, 1, 1, 1)
        self.MangaView = QtWidgets.QListWidget(self.PreciseMangaWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MangaView.setFont(font)
        self.MangaView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.MangaView.setWordWrap(True)
        self.MangaView.setObjectName("MangaView")
        self.AllListManga.addWidget(self.MangaView, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.AllListManga)
        self.gridLayout.addWidget(self.PreciseMangaWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Download Manga Novel"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.MangaName.setText(_translate("MainWindow", "DDDDDDDDDDDDDD\n"
"DDDD\n"
"DDdd"))
        self.MangaChapter.setText(_translate("MainWindow", "MangaChapter"))
        self.NovelChapter.setText(_translate("MainWindow", "NovelChapter"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.Update.setText(_translate("MainWindow", "Update"))
        self.NovelListLabel.setText(_translate("MainWindow", "Novel"))
        self.MangaListLabel.setText(_translate("MainWindow", "Manga"))
        __sortingEnabled = self.NovelView.isSortingEnabled()
        self.NovelView.setSortingEnabled(False)
        item = self.NovelView.item(0)
        item.setText(_translate("MainWindow", "Chapter 130"))
        item = self.NovelView.item(1)
        item.setText(_translate("MainWindow", "Chapter 111"))
        item = self.NovelView.item(2)
        item.setText(_translate("MainWindow", "CHAd"))
        self.NovelView.setSortingEnabled(__sortingEnabled)
